### ISSUE TITLE
List non-Zarr datasets in browser

### ISSUE THREAD

**Issue by lkluft** [orcestra-campaign/ipfsui#63]
Currently, only Zarr datasets can be shown in the ORCESTRA browser, because the necessary (meta-)data is fetched from the dataset directly. However, it would be nice to be able to show other sources (PDFs, images, ...).

This likely has large overlaps with #42 but maybe one or the other might be easier to implement first.

**Comment by lkluft** [comment]
Let's try to push this forward!

For non-Zarr datasets, I think the general idea is to add the metadata explicitly by adding a text file to the top-level directory.

The straight-forward solution would be to add a STAC-like (but reduced) item:

```json
{
  "properties": {
    "title": "BEACH dropsonde dataset (Level 3)",
    "description": "This dataset is the Level 3 BEACH dataset.",
    "keywords": ["ORCESTRA", "BEACH"],
    "license": "CC-BY-4.0",
    "references": ["https://github.com/atmdrops/pydropsonde"],
    "platform": "HALO",
    "mission": "ORCESTRA, PERCUSION, MAESTRO",
    "processing:lineage": "Level 1 ASPEN processing with Aspen V4.0.4",
    "cube:dimensions": {
      "altitude": {
        "type": "spatial",
        "axis": "z",
        "unit": "m",
      }
    },
    "cube:variables": {
      "iwv": {
        "dimensions": [
          "sonde"
        ],
        "type": "data",
        "unit": "kg m-2",
      }
    },
    "contacts": [
      {
        "name": "Helene Gloeckner",
        "emails": [
          {
            "value": "helene.gloeckner@mpimet.mpg.de",
            "roles": []
          }
        ]
      },
      {
        "name": "Theresa Mieslinger",
        "emails": [
          {
            "value": "theresa.mieslinger@mpimet.mpg.de",
            "roles": []
          }
        ]
      }
      ],
    "datetime": "2024-09-03T16:58:42.633Z",
    "start_datetime": "2024-08-09T14:26:37.333Z",
    "end_datetime": "2024-09-28T19:30:47.934Z"
  },
}
```

The advantage of this would be that users could basically get as close to the full STAC item as they want to (e.g. listing variables). One obvious disadvantage is that these items are almost impossible to create by hand. Since manual metadata addition is likely to be necessary for external datasets and/or people who do not want to adjust their workflows, it is doubtful that tools will be created for this purpose.

Alternatively, we could define our own intermediate format, which is more human writable. One could even consider to make the field names resemble the actual CF Convention attributes.

```yaml
title: "BEACH dropsonde dataset (Level 3)"
description: "This dataset is the Level 3 BEACH dataset."
keywords: "ORCESTRA", "BEACH"
license: "CC-BY-4.0"
references: "https://github.com/atmdrops/pydropsonde"
platform": "HALO"
mission": "ORCESTRA, PERCUSION, MAESTRO"
processing:lineage": "Level 1 ASPEN processing with Aspen V4.0.4"
contacts:
  - name: "Helene Gloeckner"
    email: "helene.gloeckner@mpimet.mpg.de"
  - name: "Theresa Mieslinger"
    email: "theresa.mieslinger@mpimet.mpg.de"
start_datetime: "2024-08-09T14:26:37.333Z"
end_datetime: "2024-09-28T19:30:47.934Z"
```

Although this approach is more likely to be adopted by a broader user base, it is also limited in its functions because the converter needs to be adapted.

/cc @tmieslinger @hgloeckner @d70-t

**Comment by lkluft** [comment]
After letting this sink over the weekend, I tend to prefer the user-friendly approach.

I would suggest to define a `metadata.yaml`, which allows data creators to add **the same** attributes as recommended in the [attribute convention](http://orcestra-campaign.org/attribute_convention). My reasoning is that this:
1. Reduces confusion as we are using the same set of attributes/keywords when annotating datasets in different ways (attributes vs. text file)
2. The metadata scanner works in the same way, just with a different source
3. It should be enough to serve as a proof-of-concept, no matter what we decide for in other contexts (e.g. HALO-DB 2.0)

One drawback of this approach is that information that is only available in the datasets, such as start/end dates or the variable list, would not be included. However, at this stage, this might be acceptable, or it might actually nudge users to create proper datasets. Also, a Markdown-formatted list of variables could be added to the `summary` as a fallback.

**Comment by lkluft** [comment]
I agree that it should be possible to add information beyond the global attributes of the dataset. However, we should keep the list of extensions as short as possible.

Using the item spec directly seems to cause a lot of path dependencies, because we'd have to make our mapping from CF to STAC public (thus somehow establishing a second convention) and limit ourselves to STAC in the future.

I do like your idea to use a YAML file that allows extra fields.

## Proposal

A directory that contains a file `dataset_meta.yaml` is considered a dataset. The YAML file **must** provide a `version` and an `attributes` field. The attributes **must** adhere to the [ORCESTRA Attribute Convention](https://orcestra-campaign.org/attribute_convention).

The YAML file **may** contain additional fields that are yet do the defined, e.g. `start_date`, `end_date`, `extent`.

**Example:**

```yaml
version: 1.0
attributes:
  title: BEACH dropsonde dataset (Level 3)
  summary: This dataset is the Level 3 BEACH dataset. It contains quality controlled
    dropsonde data from the ORCESTRA field campaign with a common altitude dimension.
  creator_name: Helene Gloeckner, Theresa Mieslinger, Nina Robbins
  creator_email: helene.gloeckner@mpimet.mpg.de, theresa.mieslinger@mpimet.mpg.de, nina.robbins@mpimet.mpg.de
  license: CC-BY-4.0
  featureType: trajectoryProfile
  history: "Level 1 ASPEN processing with Aspen V4.0.4"
  keywords: ORCESTRA, BEACH, Sounding, Dropsondes, Atmospheric Profiles
  platform: HALO
  project: ORCESTRA, PERCUSION, MAESTRO
  references: https://github.com/atmdrops/pydropsonde
  source: dropsondes

```

**Comment by lkluft** [comment]
Maybe we could also drop the `version` field. For other datasets it is also common that our scanner will evolve while datasets are considered persistent. If at all, data creator might make use of the `Conventions` field at state a proper version (which, however, we are not really doing so far).

**Comment by d70-t** [comment]
I mostly agree with the current version, but somehow I still feel, that extent shouldn't only be used for spatial extent, so my idea would be to go for something like:

```yaml
extent:
  temporal: ["2024-08-09T14:26:37", "2024-09-28T19:30:47"
  spatial: [-59.45647812, 1.29273319, -19.62099838, 22.03603554]
```
